### ISSUE TITLE
Map mongo database into host machine

### ISSUE THREAD

**Issue by ValarMarkhulis** [Master2022E/OnionRTC-experiment#14]
Right now it is inside of the docker container which is not setup for consistent storage.

**Comment by ValarMarkhulis** [comment]
@Thomsen96 has this been done already?

**Comment by Thomsen96** [comment]
Yes.

https://github.com/Master2022E/OnionRTC-experiment/blob/25449f85f9e4520f41d0ca6039f7740b9845cbb4/Deployment/HostA-Application/docker-compose.yaml#L40-L50
