### ISSUE TITLE
Document and setup I2P client

### ISSUE THREAD

**Issue by ValarMarkhulis** [Master2022E/OnionRTC-experiment#36]
The I2P client can host a router themselves or connect to one via SSH port forwarding and use it for connecting to the clear net.
The task might be blocked by #35

**Comment by ValarMarkhulis** [comment]
Taken from deleted/duplicated task: For I2P we have to host a I2P router that should be accessible from the internet. So we have two options: 1. host the router on the client and use the router. Or 2. we can host the router somewhere else, and have the client use the externally hosted router instead.

**Comment by Thomsen96** [comment]
Documented in the report
