### ISSUE TITLE
Test a call through Tor that is longer than 10 min

### ISSUE THREAD

**Issue by Thomsen96** [Master2022E/OnionRTC-experiment#6]
The Tor client changes the circuit every 10 minutes. 

We don't expect our tests to last longer than this. But we need to know what happens with the session when this is done.

**Comment by ValarMarkhulis** [comment]
This has been tested. The Tor circuit will available until the TCP stream has been closed. This is also described [here](https://support.torproject.org/about/change-paths/) by the Tor project.
